name: release

on:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: raos1105/x/.github/workflows/ci.yml@master
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "release"
