name: release

on:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "release"
